# -*- coding: utf-8 -*-
"""RAG(earnings2insights).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10EIj0V_jk9cY09ZLY8cGWe15-SfawekA
"""

!pip install chromadb==0.5.23 sentence-transformers nltk -q
!pip install opentelemetry-api==1.41.1 opentelemetry-sdk==1.41.1 -q

from google.colab import drive
drive.mount('/content/drive')

!unzip "/content/drive/MyDrive/Earnings2Insights.zip" -d "/content/drive/MyDrive/"

import os
import nltk
import chromadb
from nltk.tokenize import sent_tokenize
from sentence_transformers import SentenceTransformer

nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
print("All imports done")

# ── Fixed paths — filter .DS_Store + correct filename ──
DRIVE_BASE        = "/content/drive/MyDrive"
CHROMA_PATH       = f"{DRIVE_BASE}/findebate_chromadb"
ECTSUM_PATH       = f"{DRIVE_BASE}/Earnings2Insights/Earnings2Insights/ECTsum"
PROFESSIONAL_PATH = f"{DRIVE_BASE}/Earnings2Insights/Earnings2Insights/Professional"

print("Loading FinLang model...")
model = SentenceTransformer("FinLang/finance-embeddings-investopedia")
print("Model loaded")

chroma_client = chromadb.PersistentClient(path=CHROMA_PATH)

# ── SAFE: only delete if you explicitly set this to True ──
FRESH_START = False   # ← set True ONLY if you want to wipe and re-index

if FRESH_START:
    try:
        chroma_client.delete_collection("findebate_rag")
        print("Old collection deleted")
    except:
        pass

collection = chroma_client.get_or_create_collection(
    name="findebate_rag",
    metadata={"hnsw:space": "cosine"}
)

print(f"Collection ready: '{collection.name}'")
print(f"Current chunk count: {collection.count()}")

def chunk_text(text, max_tokens=200):
    """
    Context-sensitive segmentation: paragraph -> sentence -> token.
    Exactly mirrors Section 2.1 of the FinDebate paper.

    Priority order:
    1. Preserve paragraph boundaries
    2. Preserve sentence boundaries
    3. Split at token level only when sentence exceeds max_tokens
    """
    paragraphs = text.split("\n\n")
    chunks = []

    for para in paragraphs:
        para = para.strip()
        if not para:
            continue

        sentences = sent_tokenize(para)
        current_chunk = []

        for sent in sentences:
            words = sent.split()

            if len(current_chunk) + len(words) <= max_tokens:
                # Sentence fits — add to current chunk
                current_chunk.extend(words)
            else:
                # Current chunk full — save it
                if current_chunk:
                    chunks.append(" ".join(current_chunk))

                # Sentence itself too long — split at token level
                if len(words) > max_tokens:
                    for i in range(0, len(words), max_tokens):
                        chunks.append(" ".join(words[i:i + max_tokens]))
                    current_chunk = []
                else:
                    current_chunk = words

        if current_chunk:
            chunks.append(" ".join(current_chunk))

    # Drop fragments under 20 chars — too short to carry financial meaning
    return [c for c in chunks if len(c.strip()) > 20]

# Wipe old collection (6344 chunks were from wrong data)
chroma_client.delete_collection("findebate_rag")
collection = chroma_client.get_or_create_collection(
    name="findebate_rag",
    metadata={"hnsw:space": "cosine"}
)
print("Fresh collection ready")

def ingest_subset(base_path, doc_type):
    """
    Indexes all source.md files from one dataset subset into ChromaDB.

    Args:
        base_path : path to ECTsum/ or Professional/ folder
        doc_type  : "earnings" | "analyst_report"
                    stored as metadata, used by retrieve() for filtering

    Note:
        Chunks are NOT pre-labelled with dimensions.
        Multi-dimensional retrieval is achieved at QUERY TIME
        by running different queries against the full index.
        This is the correct interpretation of Appendix B.
    """
    if not os.path.exists(base_path):
        print(f"❌ Path not found: {base_path}")
        return 0

    folders = [
        f for f in os.listdir(base_path)
        if not f.startswith('.')
        and os.path.isdir(os.path.join(base_path, f))
    ]

    total_chunks = 0
    skipped      = 0

    for folder in folders:
        source_path = os.path.join(base_path, folder, "source", "source.md")

        if not os.path.exists(source_path):
            print(f"  ⚠️  No source.md in {folder}, skipping")
            skipped += 1
            continue

        with open(source_path, "r", encoding="utf-8") as f:
            text = f.read()

        chunks = chunk_text(text)

        if not chunks:
            print(f"  ⚠️  No chunks from {folder}, using full text as fallback")
            chunks = [text[:3000]]

        embeddings = model.encode(
            chunks,
            batch_size=64,
            convert_to_numpy=True,
            show_progress_bar=False
        ).tolist()

        ids = [
            f"{doc_type}_{folder}_chunk_{j}"
            for j in range(len(chunks))
        ]
        metadatas = [
            {
                "source_file" : folder,
                "type"        : doc_type,
                "chunk_index" : j
            }
            for j in range(len(chunks))
        ]

        try:
            existing_ids = set(collection.get(ids=ids)["ids"])
        except Exception:
            existing_ids = set()

        new_mask = [i for i, cid in enumerate(ids) if cid not in existing_ids]

        if new_mask:
            collection.add(
                documents  = [chunks[i]     for i in new_mask],
                embeddings = [embeddings[i] for i in new_mask],
                ids        = [ids[i]        for i in new_mask],
                metadatas  = [metadatas[i]  for i in new_mask]
            )
            total_chunks += len(new_mask)

    print(f"✅ {doc_type:>15} | {len(folders)-skipped:>3} docs "
          f"| {total_chunks:>5} new chunks indexed "
          f"| {skipped} skipped")
    return total_chunks

import os

# Skip .DS_Store and get first real folder
ectsum_folders = [f for f in os.listdir(ECTSUM_PATH)
                  if not f.startswith('.') and
                  os.path.isdir(os.path.join(ECTSUM_PATH, f))]

pro_folders = [f for f in os.listdir(PROFESSIONAL_PATH)
               if not f.startswith('.') and
               os.path.isdir(os.path.join(PROFESSIONAL_PATH, f))]

print(f"ECTsum: {len(ectsum_folders)} real folders")
print(f"Professional: {len(pro_folders)} real folders")

# Check actual filenames in first real folder
print("\nECTsum sample:")
sample = os.path.join(ECTSUM_PATH, ectsum_folders[0])
print(f"  Folder: {ectsum_folders[0]}")
print(f"  Files: {os.listdir(sample)}")

print("\nProfessional sample:")
sample2 = os.path.join(PROFESSIONAL_PATH, pro_folders[0])
print(f"  Folder: {pro_folders[0]}")
print(f"  Files: {os.listdir(sample2)}")

print("Starting ingestion...\n")
n1 = ingest_subset(ECTSUM_PATH,       doc_type="earnings")
n2 = ingest_subset(PROFESSIONAL_PATH, doc_type="analyst_report")
print(f"\nTotal chunks in ChromaDB: {collection.count()}")

def retrieve(query, top_k=5, doc_type_filter=None):
    """
    Semantic retrieval against the full index.

    Args:
        query           : natural language query string
        top_k           : number of results to return
        doc_type_filter : "earnings" | "analyst_report" | None (both)

    Returns:
        list of dicts — chunk, source_file, chunk_id, type, score
    """
    q_emb       = model.encode([query], convert_to_numpy=True).tolist()
    where_clause = {"type": doc_type_filter} if doc_type_filter else None

    results = collection.query(
        query_embeddings = q_emb,
        n_results        = top_k,
        where            = where_clause,
        include          = ["documents", "metadatas", "distances"]
    )

    output = []
    for doc, meta, dist in zip(
        results["documents"][0],
        results["metadatas"][0],
        results["distances"][0]
    ):
        output.append({
            "chunk"       : doc,
            "source_file" : meta["source_file"],
            "chunk_id"    : meta["chunk_index"],
            "type"        : meta["type"],
            "score"       : round(1 - dist, 4)  # cosine distance → similarity
        })

    return output

# ── 4 dimensions from Appendix B of the paper ────────────────────────────────
DIMENSION_QUERIES = {
    "general_financial": [
        "financial performance revenue earnings beat miss surprise results",
        "guidance outlook forecast expectations future performance strategy",
        "growth trends margin expansion profitability cash flow competitive"
    ],
    "specialized_metrics": [
        "net interest margin NIM loan deposits credit quality asset quality",
        "non-performing assets NPAs charge-offs provision loan losses problem loans",
        "return on assets ROA return on equity ROE efficiency ratio capital adequacy tier 1"
    ],
    "market_sentiment_risk": [
        "management confidence sentiment optimistic cautious positive negative tone",
        "risks challenges concerns headwinds uncertainties market conditions volatility",
        "credit risk operational risk market risk liquidity risk management hedging"
    ],
    "multi_query_integration": [
        "short-term immediate near-term weekly monthly quarterly timeline events",
        "comparative performance benchmarking cross-functional analysis trends",
        "comprehensive integrated multi-dimensional longitudinal performance tracking"
    ]
}

def retrieve_by_dimension(dimension, doc_type_filter=None, top_k=5):
    """
    Runs all queries for a given dimension and merges results.
    Deduplicates by chunk ID. Returns top_k by score.

    This is the correct Appendix B implementation:
    same index, different queries per dimension — not pre-labelled buckets.
    """
    if dimension not in DIMENSION_QUERIES:
        raise ValueError(f"Unknown dimension '{dimension}'. "
                         f"Choose from: {list(DIMENSION_QUERIES.keys())}")

    seen   = set()
    merged = []

    for query in DIMENSION_QUERIES[dimension]:
        results = retrieve(query, top_k=top_k, doc_type_filter=doc_type_filter)
        for r in results:
            uid = f"{r['source_file']}_chunk_{r['chunk_id']}"
            if uid not in seen:
                seen.add(uid)
                merged.append(r)

    # Sort by score, return top_k
    merged.sort(key=lambda x: x["score"], reverse=True)
    return merged[:top_k]


def retrieve_all_dimensions(doc_type_filter=None, top_k=3):
    """
    Runs all 4 dimensions. Returns dict keyed by dimension name.
    This is what P2/P3 agents will call to get their context.
    """
    return {
        dim: retrieve_by_dimension(dim, doc_type_filter=doc_type_filter, top_k=top_k)
        for dim in DIMENSION_QUERIES
    }

def get_agent_context(source_file=None, top_k=3):
    fetch_k = top_k * 10 if source_file else top_k

    dims = {}
    for dim in DIMENSION_QUERIES:
        results = retrieve_by_dimension(dim, top_k=fetch_k)
        if source_file:
            results = [r for r in results
                      if r["source_file"] == source_file][:top_k]
        dims[dim] = results

    return {
        "earnings_agent"  : dims["general_financial"] + dims["specialized_metrics"],
        "market_agent"    : dims["general_financial"] + dims["multi_query_integration"],
        "sentiment_agent" : dims["market_sentiment_risk"],
        "valuation_agent" : dims["specialized_metrics"] + dims["general_financial"],
        "risk_agent"      : dims["market_sentiment_risk"] + dims["specialized_metrics"]
    }

print("=" * 60)
print("RAG RETRIEVAL VALIDATION")
print("=" * 60)

# ── Test 1: Basic retrieval ───────────────────────────────────
print("\n── Test 1: Basic retrieval (no filter) ──")
results = retrieve("revenue growth earnings per share guidance", top_k=3)
for r in results:
    print(f"  [{r['score']}] {r['source_file']} ({r['type']})")
    print(f"  {r['chunk'][:150]}...\n")

# ── Test 2: Filter by doc type ────────────────────────────────
print("\n── Test 2: Earnings only ──")
results = retrieve("net interest margin capital adequacy", top_k=2,
                   doc_type_filter="earnings")
for r in results:
    print(f"  [{r['score']}] {r['source_file']} ({r['type']})")
    print(f"  {r['chunk'][:150]}...\n")

print("\n── Test 3: Analyst reports only ──")
results = retrieve("investment recommendation buy sell price target", top_k=2,
                   doc_type_filter="analyst_report")
for r in results:
    print(f"  [{r['score']}] {r['source_file']} ({r['type']})")
    print(f"  {r['chunk'][:150]}...\n")

# ── Test 4: Multi-dimensional retrieval ──────────────────────
print("\n── Test 4: All 4 dimensions ──")
all_dims = retrieve_all_dimensions(top_k=2)
for dim, results in all_dims.items():
    print(f"\n  [{dim}] — {len(results)} chunks")
    for r in results[:1]:  # show 1 per dim to keep output clean
        print(f"    [{r['score']}] {r['source_file']}")
        print(f"    {r['chunk'][:120]}...")

# ── Test 5: Agent context ─────────────────────────────────────
print("\n── Test 5: Agent context ──")
context = get_agent_context(top_k=2)
for agent, chunks in context.items():
    print(f"  {agent}: {len(chunks)} chunks retrieved")

# ── Final count ───────────────────────────────────────────────
print(f"\n{'='*60}")
print(f"Total chunks in ChromaDB: {collection.count()}")
print(f"{'='*60}")