# -*- coding: utf-8 -*-
"""RAG_PART1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfTux_TqAmkZs7SDdQuy45PoCzR_KlNB
"""

!pip install faiss-cpu sentence-transformers nltk -q

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
import os
import nltk
import pickle
from nltk.tokenize import sent_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')
print("All imports done")

!git clone https://github.com/rajdeep345/ECTSum.git

ects_path = "/content/ECTSum/data/final/train/ects"
files = [f for f in os.listdir(ects_path) if f.endswith(".txt")]
print(f"Found {len(files)} transcripts")
print("Sample files:", files[:3])

print("Loading FinLang model...")
model = SentenceTransformer("FinLang/finance-embeddings-investopedia")
print("Model loaded successfully")

def chunk_text(text, max_tokens=200):
    """
    Recursive chunking: paragraph -> sentence -> token
    Mirrors the context-sensitive segmentation in the paper (Section 2.1)
    """
    paragraphs = text.split("\n\n")
    chunks = []

    for para in paragraphs:
        para = para.strip()
        if not para:
            continue

        sentences = sent_tokenize(para)
        current_chunk = []

        for sent in sentences:
            words = sent.split()

            if len(current_chunk) + len(words) <= max_tokens:
                # Fits in current chunk — add it
                current_chunk.extend(words)
            else:
                # Current chunk is full — save it
                if current_chunk:
                    chunks.append(" ".join(current_chunk))

                # If single sentence is too long, split at token level
                if len(words) > max_tokens:
                    for i in range(0, len(words), max_tokens):
                        chunks.append(" ".join(words[i:i+max_tokens]))
                    current_chunk = []
                else:
                    current_chunk = words

        # Save any remaining words
        if current_chunk:
            chunks.append(" ".join(current_chunk))

    return [c for c in chunks if len(c.strip()) > 20]  # drop tiny fragments

all_chunks = []
all_ids = []
skipped = 0

print(f"Processing {len(files)} transcripts...")

for i, fname in enumerate(files):
    file_path = os.path.join(ects_path, fname)

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            text = f.read()

        chunks = chunk_text(text)
        all_chunks.extend(chunks)
        all_ids.extend([f"{fname}_chunk_{j}" for j in range(len(chunks))])

        if (i + 1) % 100 == 0:
            print(f"  Processed {i+1}/{len(files)} files | Total chunks: {len(all_chunks)}")

    except Exception as e:
        print(f"  Skipped {fname}: {e}")
        skipped += 1

print(f"\nDone. {len(all_chunks)} total chunks from {len(files)-skipped} transcripts")

print(f"Encoding {len(all_chunks)} chunks with FinLang...")
print("This will take a few minutes...")

embeddings = model.encode(
    all_chunks,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True
)

embeddings = embeddings.astype("float32")
print(f"\nEmbedding shape: {embeddings.shape}")

dim = embeddings.shape[1]

# Normalize for cosine similarity
faiss.normalize_L2(embeddings)

# Build flat index (exact search — best for your dataset size)
index = faiss.IndexFlatIP(dim)
index.add(embeddings)

print(f"FAISS index built: {index.ntotal} vectors, {dim} dimensions")

faiss.write_index(index, "/content/findebate.index")

with open("/content/findebate_chunks.pkl", "wb") as f:
    pickle.dump({
        "chunks": all_chunks,
        "ids": all_ids
    }, f)

print("Saved:")
print("  /content/findebate.index")
print("  /content/findebate_chunks.pkl")

def retrieve(query, top_k=5):
    q_emb = model.encode([query], convert_to_numpy=True).astype("float32")
    faiss.normalize_L2(q_emb)
    scores, indices = index.search(q_emb, top_k)

    results = []
    for score, idx in zip(scores[0], indices[0]):
        results.append({
            "chunk": all_chunks[idx],
            "id": all_ids[idx],
            "score": round(float(score), 4)
        })
    return results

# Test with a financial query
results = retrieve("net interest margin revenue growth earnings per share", top_k=3)

for i, r in enumerate(results):
    print(f"\n--- Result {i+1} (score: {r['score']}) ---")
    print(f"Source: {r['id']}")
    print(f"Text: {r['chunk'][:300]}...")

# Run this at the start of any future session
# instead of re-encoding everything

index = faiss.read_index("/content/findebate.index")

with open("/content/findebate_chunks.pkl", "rb") as f:
    data = pickle.load(f)
    all_chunks = data["chunks"]
    all_ids = data["ids"]

print(f"Loaded index with {index.ntotal} vectors")
print(f"Loaded {len(all_chunks)} chunks")

print("\n===== RAG RETRIEVAL VALIDATION =====\n")

queries = [
    "revenue growth and earnings performance",
    "risk factors and challenges",
    "management sentiment and outlook"
]

summ_path = "/content/ECTSum/data/final/train/gt_summaries"

for q in queries:
    print(f"\n🔎 Query: {q}")

    results = retrieve(q, top_k=2)

    for i, r in enumerate(results):
        print(f"\n--- Result {i+1} (score: {r['score']}) ---")
        print(r["chunk"][:250], "...")

    # Optional: compare with summary (first file only for demo)
    fname = results[0]["id"].split("_chunk_")[0]

    try:
        with open(os.path.join(summ_path, fname), "r") as f:
            summary = f.read()

        print("\n📄 Ground Truth Summary (excerpt):")
        print(summary[:250], "...")

    except:
        print("\n(No summary found)")